apiVersion: aws.platform.upbound.io/v1alpha1
kind: XNetwork
metadata:
  name: ref-aws-network
  annotations:
    crossplane.io/render-composition-path: apis/network/composition.yaml
    crossplane.io/render-function-path: examples/functions.yaml
spec:
  parameters:
    id: platform-ref-aws
    region: us-east-1