apiVersion: aws.caas.upbound.io/v1alpha1
kind: XCluster
metadata:
  name: aws-spoke-01
spec:
  parameters:
    id: aws-spoke-01
    region: eu-central-1
    version: "1.28"
    nodes:
      count: 5
      instanceType: t3.large
    gitops:
      url: https://github.com/upbound/caas-cluster-configuration
  writeConnectionSecretToRef:
    name: aws-spoke-01-kubeconfig
