on:
  pull_request:
#    branches: [main]

name: Crossplane Dynamic Diff

jobs:
  pr:
    name: prepare
    runs-on: ubuntu-latest
    steps:
      - name: diff
        uses: pedjak/crossplane-diff-action@action
        with:
          dir: examples
<<<<<<< HEAD
          github-token: ${{ secrets.GITHUB_TOKEN }}
=======
          token: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> 4432273 (wip)
