on:
  pull_request:
    branches: [main]

name: Crossplane Dynamic Diff

jobs:
  pr:
    name: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all 
      - name: Check out current commit
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
      - name: Install Crossplane CLI
        run: go install github.com/crossplane/crossplane/cmd/crank@latest

      # Split input files into an array
      - name: Split input files
        run: |
          IFS=',' read -ra INPUT_FILES <<< "${{ env.INPUT_FILES }}"
          echo "INPUT_FILES=${INPUT_FILES[*]}" >> $GITHUB_ENV

      # Run a dynamic job for each input file
      - name: Run Dynamic Jobs
        run: |
          for files in "${INPUT_FILES[@]}"; do
            IFS=',' read -ra FILE_ARRAY <<< "$files"
            for file in "${FILE_ARRAY[@]}"; do
              crank beta render $file >> diff-${file//\//-}.yaml
            done
          done

      # Store outputs as artifacts
      - name: Store outputs
        uses: actions/upload-artifact@v3
        with:
          name: diff-pr-${{ github.sha }}
          path: diff-*.yaml

  main:
    name: diff
    needs: [pr]
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      # Check out the main branch
      - name: Check out main
        uses: actions/checkout@v4
        with:
          ref: main

      # Download artifacts from the dynamic job
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: diff-pr-${{ github.sha }}

      # Run a dynamic job for each input file on the main branch
      - name: Run Dynamic Jobs on main
        run: |
          INPUT_FILES=${{ env.INPUT_FILES }}
          for files in "${INPUT_FILES[@]}"; do
            IFS=',' read -ra FILE_ARRAY <<< "$files"
            for file in "${FILE_ARRAY[@]}"; do
              crank beta render $file >> diff-main-${file//\//-}.yaml
            done
          done

      # Store outputs as artifacts
      - name: Store main outputs
        uses: actions/upload-artifact@v3
        with:
          name: diff-main-${{ github.sha }}
          path: diff-main-*.yaml

      # Diff the outputs between PR and main
      - name: Diff
        id: diff_rev
        run: |
          for files in "${INPUT_FILES[@]}"; do
            IFS=',' read -ra FILE_ARRAY <<< "$files"
            for file in "${FILE_ARRAY[@]}"; do
              DELTA=$(diff -u diff-main-${file//\//-}.yaml diff-pr-${file//\//-}.yaml || true)
              echo "DELTA_${file//\//-}<<EOF" >> $GITHUB_ENV
              echo "$DELTA" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
            done
          done

      # Auto comment with diffs
      - name: Auto Comment
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestSynchronize: |
            👋 @{{ author }}
            
            This is the code diff:
            
            ```diff
            ${{ env.DELTA_*.yaml }}
            ```
