name: Crossplane Dynamic Diff

on:
  pull_request:

jobs:
  diff:
    name: diff
    runs-on: ubuntu-latest
    steps:
      - name: Check out current commit
        uses: actions/checkout@v4

      - name: Crossplane Dynamic Diff
        uses: ./.
        with:
          # process XRs from the given directory
          dir: examples 
          github-token: ${{ secrets.GITHUB_TOKEN }}
